{%- if cookiecutter.hook_black == "y" %}
[tool.black]
line-length = 100
{% endif %}

{%- if cookiecutter.hook_isort == "y" %}
[tool.isort]
known_first_party = "{{ cookiecutter.project_name }}"
line_length = 100
### for compatibility with black
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip_glob="**/__init__.py"
{% endif %}