{%- if cookiecutter.hook_black == "y" %}
[tool.black]
line-length = 100
{% endif %}

{%- if cookiecutter.hook_isort == "y" %}
[tool.isort]
known_first_party = "{{ cookiecutter.project_name }}"
line_length = 100
### for compatibility with black
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip_glob="**/__init__.py"
{% endif %}

{%- if cookiecutter.hook_pytest == "y" %}
[tool.pytest.ini_options]
minversion = "6.0"
log_cli = 1
log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s [%(levelname)s] %(module)s.%(funcName)s.%(lineno)d: %(message)s"
log_cli_date_format = "{{ cookiecutter.__date }}"
addopts = "-v --capture=sys tests"
norecursedirs = "node_modules dist"
{% endif %}

{%- if cookiecutter.hook_vulture == "y" %}
[tool.vulture]
paths = ["{{ cookiecutter.project_name }}"]
{% endif %}